#!/bin/sh
#
#
# install/doinst.sh - to be done after extraction
#
# Copyright (c) 1996-2002 SuSE Linux AG, Nuernberg, Germany. 
#
#
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/00b.change_scripts.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/00b.change_scripts.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/00b.change_scripts.sh || ln -s ../../shared/00b.change_scripts.sh map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/00b.change_scripts.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/04b.class_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/04b.class_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/04b.class_reads.template.R || ln -s ../../shared/04b.class_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/04b.class_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/05b.sum_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/05b.sum_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/05b.sum_reads.template.R || ln -s ../../shared/05b.sum_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/05b.sum_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/08.write_stats_and_tracks.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/08.write_stats_and_tracks.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/08.write_stats_and_tracks.R || ln -s ../../shared/08.write_stats_and_tracks.R map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/08.write_stats_and_tracks.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/09b.delete_files.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/09b.delete_files.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/09b.delete_files.sh || ln -s ../../shared/09b.delete_files.sh map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/other/09b.delete_files.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/00b.change_scripts.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/00b.change_scripts.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/00b.change_scripts.sh || ln -s ../../shared/00b.change_scripts.sh map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/00b.change_scripts.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/04b.class_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/04b.class_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/04b.class_reads.template.R || ln -s ../../shared/04b.class_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/04b.class_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/05b.sum_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/05b.sum_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/05b.sum_reads.template.R || ln -s ../../shared/05b.sum_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/05b.sum_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/08.write_stats_and_tracks.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/08.write_stats_and_tracks.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/08.write_stats_and_tracks.R || ln -s ../../shared/08.write_stats_and_tracks.R map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/08.write_stats_and_tracks.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/09b.delete_files.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/09b.delete_files.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/09b.delete_files.sh || ln -s ../../shared/09b.delete_files.sh map_to_genome/other/pipeline_old/class_reads.chunks/paired_end/mouse/09b.delete_files.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/00b.change_scripts.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/00b.change_scripts.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/00b.change_scripts.sh || ln -s ../../shared/00b.change_scripts.sh map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/00b.change_scripts.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/04b.class_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/04b.class_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/04b.class_reads.template.R || ln -s ../../shared/04b.class_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/04b.class_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/05b.sum_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/05b.sum_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/05b.sum_reads.template.R || ln -s ../../shared/05b.sum_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/05b.sum_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/08.write_stats_and_tracks.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/08.write_stats_and_tracks.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/08.write_stats_and_tracks.R || ln -s ../../shared/08.write_stats_and_tracks.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/08.write_stats_and_tracks.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/09b.delete_files.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/09b.delete_files.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/09b.delete_files.sh || ln -s ../../shared/09b.delete_files.sh map_to_genome/other/pipeline_old/class_reads.chunks/single_end/small_RNAseq/09b.delete_files.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/00b.change_scripts.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/00b.change_scripts.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/00b.change_scripts.sh || ln -s ../../shared/00b.change_scripts.sh map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/00b.change_scripts.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/04b.class_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/04b.class_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/04b.class_reads.template.R || ln -s ../../shared/04b.class_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/04b.class_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/05b.sum_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/05b.sum_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/05b.sum_reads.template.R || ln -s ../../shared/05b.sum_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/05b.sum_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/08.write_stats_and_tracks.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/08.write_stats_and_tracks.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/08.write_stats_and_tracks.R || ln -s ../../shared/08.write_stats_and_tracks.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/08.write_stats_and_tracks.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/09b.delete_files.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/09b.delete_files.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/09b.delete_files.sh || ln -s ../../shared/09b.delete_files.sh map_to_genome/other/pipeline_old/class_reads.chunks/single_end/other/09b.delete_files.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/00b.change_scripts.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/00b.change_scripts.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/00b.change_scripts.sh || ln -s ../../shared/00b.change_scripts.sh map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/00b.change_scripts.sh
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/04b.class_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/04b.class_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/04b.class_reads.template.R || ln -s ../../shared/04b.class_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/04b.class_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/05b.sum_reads.template.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/05b.sum_reads.template.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/05b.sum_reads.template.R || ln -s ../../shared/05b.sum_reads.template.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/05b.sum_reads.template.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/08.write_stats_and_tracks.R 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/08.write_stats_and_tracks.R $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/08.write_stats_and_tracks.R || ln -s ../../shared/08.write_stats_and_tracks.R map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/08.write_stats_and_tracks.R
rm -f map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/09b.delete_files.sh 2>/dev/null || echo map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/09b.delete_files.sh $SLDIRERROR >&2
test -e map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/09b.delete_files.sh || ln -s ../../shared/09b.delete_files.sh map_to_genome/other/pipeline_old/class_reads.chunks/single_end/mouse/09b.delete_files.sh
